name: Build & release liascript-preview-web plugin
on: push
jobs:
  release-project:
    name: Release liascript-preview-web plugin
    runs-on: ubuntu-latest
    needs: build-project
    steps:
      - name: Download plugin
        uses: actions/download-artifact@v2
      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-project:
    name: Build liascript-preview-web plugin
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install NPM dependencies
        run: npm install
      - name: Install vsce
        run: npm install -g vsce
      - name: Build plugin
        run: vsce package
      - name: Upload plugin
        uses: actions/upload-artifact@v2
        with:
          path: '*.vsix'
